spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_taxi
    username: postgres
    password: root123

  jpa:
    hibernate:
      ddl-auto: create

  security:
    filter:
      order: -100

security:

  jwt:
    secret: ${JWT_SECRET:change-me-256bit-key}   # 32+ bayt bo'lsin
    access-exp-min: 30
    refresh-exp-days: 7
