spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_taxi
    username: postgres
    password: root123

  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update

security:
  jwt:
    issuer: my_taxi
    audience: my.taxi.app
    secret-base64: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-exp-min: 10
    refresh-exp-days: 14
    cookie:
      refresh-name: "refresh_token"
      same-site: "Strict"

