spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_taxi
    username: postgres
    password: root123

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: update

application:
  security:
    jwt:
      issuer: my_taxi_app
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000000
      refresh-token:
        expiration: 6048000000
